FROM manjunathgk/java8-ubuntu16:latest
RUN mkdir /src
ADD myserver.java /src
ADD PingPongServer.java /src
ADD PingServerFactory.java /src
ADD ServerImpl.java /src
RUN mkdir /src/rmi
ADD rmi /src/rmi

